action = compile

.PHONY: all planck preonic sofle moonlander ramaworks

all: planck preonic sofle moonlander ramaworks

planck:
	qmk ${action} -kb planck/ez/glow -km krig

preonic:
	qmk ${action} -kb preonic/rev3 -km krig

sofle:
	qmk ${action} -kb sofle -km krig

moonlander:
	qmk ${action} -kb moonlander -km krig

ramaworks:
	qmk ${action} -kb wilba_tech/rama_works_m50_a -km krig

