// nav layer

#define L_NAV_L1  GUI__Q, CW_TOGG, CMD_GRV, CMD_TAB, LCTL_W
#define L_NAV_L2 KC_LALT, KC_LCTL, KC_LGUI, KC_LSFT, KC_RALT
#define L_NAV_L3  GUI__Z,  GUI__X,  GUI__C,  GUI__V,  GUI__B

#define L_NAV_R1  KC_INS, KC_HOME,   KC_UP,  KC_END, SWE_AA
#define L_NAV_R2  KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, SWE_AE
#define L_NAV_R3 KC_WBAK, KC_PGDN, KC_PGUP, KC_WFWD, SWE_OE

